jobs:
- job: Linux_Nuphar_CI_Dev
  pool: Linux-CPU
  steps:
    - template: templates/set-test-data-variables-step.yml

    - task: CmdLine@2
      displayName: 'Clean untagged docker images'
      inputs:
        script: |
          docker container prune -f
          docker image prune -f
        workingDirectory: $(Build.BinariesDirectory)
      continueOnError: true
      condition: always()

    - task: CmdLine@2
      displayName: 'Download azcopy'
      inputs:
        script: |
          curl -so azcopy.tar.gz -L 'https://aka.ms/downloadazcopy-v10-linux'
          tar -zxvf azcopy.tar.gz --strip 1
        workingDirectory: $(Build.BinariesDirectory)

    - script: 'tools/ci_build/github/linux/run_dockerbuild.sh -o ubuntu16.04 -d nuphar -r $(Build.BinariesDirectory)'
      displayName: 'Build and test'

    - task: PublishTestResults@2
      displayName: 'Publish unit test results'
      inputs:
        testResultsFiles: '**/*.results.xml'
        searchFolder: '$(Build.BinariesDirectory)'
        testRunTitle: 'Unit Test Run'
      condition: succeededOrFailed()

    - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
      displayName: 'Component Detection'
      condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))

    - template: templates/clean-agent-build-directory-step.yml
